### ISSUE TITLE
Support for AlpineJS v3

### ISSUE THREAD

**Issue by abasse** [pinecone-router/router#12]
Are there any plans to support Alpine JS v3?

**Comment by rehhouari** [comment]
I've tried to upgrade it but it turned out more complicated than I thought since the plugins API changed.. I went with trying to create a new one that uses new features but I wasn't able to do so, a lot of things happened including my PC's disk failing.

I can recommend [page.js](https://github.com/visionmedia/page.js) as an alternative that's framework-independent and works fine with Alpine.js

If anyone would like to take this I'd be happy to accept push requests and sorry for the inconvenience.

Meanwhile I'll try once again

**Comment by caturandi-labs** [comment]
please support for Alpine v3 @rehhouari  ... really appreciated

**Comment by rehhouari** [comment]
> please support for Alpine v3 @rehhouari ... really appreciated

the disk on my computer failed/broke, i can't work on it:(
I actually tried a few times but the plugin system changed; i might create a new lite version for alpine 3 but not promising anything because of the issues i'm having

**Comment by hendrikschneider** [comment]
Any updates on this?

**Comment by rehhouari** [comment]
I've updated it to Alpine v3, done some testing, it's almost backwards compatible except you no longer need `x-router` and the [settings are set differently now.](https://github.com/pinecone-router/router#settings)

sorry for taking long, even after I was able to work on it I didn't get through with it cause I was burnt out. Just pulled an all-nighter on this so I may have missed some edge-cases but both the examples are working so I'll call it a day.

**Comment by abasse** [comment]
That's great news, thank you.

**Comment by davidwebca** [comment]
Thanks so much! I'll try to test it and get feedback.
