### ISSUE TITLE
Routes with <template> tags not rendered

### ISSUE THREAD

**Issue by go4cas** [pinecone-router/router#34]
First off, thanks for the great library!

I have a number of pages, in external .html files. These all use the https://github.com/vimeshjs/vimesh-ui Alpine component library, to allow me to include re-usable components on these pages. Therefore, each of these pages will be wrapped in a `<template>`.

This results in the route not being rendered.

I have done a simple test:
`index.html`:
```html
<template x-route="/" x-template="/pages/test.html"></template>
```

`/pages/test.html`:
```html
<template>
  <div class="text-white text-4xl">HOME</div>
</template>
```
^^^ this does not render

`/pages/test.html`:
```html
<div class="text-white text-4xl">HOME</div>
```
^^^ this renders correctly

Is there any other way to render these?

**Comment by rehhouari** [comment]
The `x-template` directive simply fetches the file and show it conditionally the same way `x-if` does it.

I am not familiar with the vimesh library but it seems you're missing the `x-component` directive?
this is what I see in their README:
```html
<vui-greeting>Vimesh UI</vui-greeting>

<template x-component="greeting">
    <h1>Hello <slot></slot></h1>
</template>
```
So shouldn't `/pages/test.html` contain:
```html
<vui-greeting>Vimesh UI</vui-greeting>
```
then somewhere else you put the `template` declaration?

`<template>` never renders on it's own, it's not a bug with this router, it's an HTML standard. So I assume it does get added to the document it just doesn't show because it's a template tag. (you can test this by using devtools I haven't yet)

**Comment by go4cas** [comment]
I have removed the `<template>` wrappers from the pages. Now all the routes are rendering correctly, while I can still embed components inside pages.
