### ISSUE TITLE
Hash routing without redirection

### ISSUE THREAD

**Issue by mzwygart** [pinecone-router/router#42]
**Is your feature request related to a problem? Please describe.**
I am trying to use Pinecone Router on a WordPress site to handle routing for certain components. However, when using hash routing in this setup, the browser's back button does not function as expected.

**Describe the solution you'd like**
I would like to have the option to use hash routing without Pinecone automatically adding /#/ to the URL.

**Comment by rehhouari** [comment]
I can't really figure out how to do that, does setting `window.PineconeRouter.settings.interceptLinks = false` not solve this?

if not try to edit [this line](https://github.com/pinecone-router/router/blob/f7069b1f5072f143581ce2ecdaa10f2dd3db94ab/src/index.ts#L611) locally and build using `pnpm build`, to see if it helps

cant do much since that usecase is beyond the scope of this project
hope youve figured it out or found an alternative!
